# Binary Classification (Logistic Regression) 

## Overview
Binary classification is one of the most fundamental and common tasks in machine learning and deep learning. 
At its core, it's a supervised learning problem where the goal is to categorize input data into one of two possible classes or categories. 
Think of it as teaching a machine to make a "yes" or "no" decision.
Examples of binary classification's applications are:

- Spam Detection: Classifying an email as either 'spam' or 'not spam'.
- Medical Diagnosis: Determining if a patient has a certain disease.
- Credit Scoring: Deciding whether a loan applicant is a 'good credit risk' or a 'bad credit risk'.
- Collision Detection: Differentiate deliberate environmental interaction forces from unintended physical impacts.

A sigmoid activated multi-input, single-output linear model is a decent candidate for this job.
In this practice, you'll train such a model to categorize samples from a toy dataset into two classes.

## Problem Definition
Using synthetic data generated by [`make_circles`](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_circles.html#sklearn.datasets.make_circles), construct a model to categorize points in 2D space into two clusters.

## Objectives
- Train a simple neural network model.
    - Apply sigmoid activation on a linear model.
    - Implement binary cross entropy evaluation.
    - Practice vectorized computing.
- Train an upgraded model with hidden features.
- Assess model's performance using a variety of metrics.


## Exercises:
<font color=#582C83>

1. (5%) Data Pre-Processing
2. (10%) Model N01 Construction
3. (10%) Model Assessments
4. (5%) Gradient of BCE Loss
5. (10%) Model N01 Optimization
6. (10%) Model N11 Construction
7. (20%) Gradient of Loss Back Propagation
8. (15%) Model N11 Optimization
9. (5%) Classification Metrics
10. (10%) Validation Analyses

</font>


## 1. Load and Pre-Process Training Dataset

The dataset, 
$$\mathcal{D} = \{\mathbf{X}, \mathbf{y}\} = \begin{bmatrix} ^{(1)} \mathbf{x} & ^{(1)} y \\ ^{(2)} \mathbf{x} & ^{(2)} y \\ \vdots \\ ^{(M)} \mathbf{x} & ^{(M)} y \end{bmatrix}$$
consists $M$ samples.

Each sample has $N$ features: $^{(i)} \mathbf{x} = [^{(i)} x_1, ^{(i)} x_2, \dots, ^{(i)} x_N]$ and is labeled as $^{(i)} y \in \{0, 1\}$, where $i \in \{1, 2, ..., M\}$.

In this practice, we make a toy dataset using [scikit-learn](https://scikit-learn.org/stable/index.html)'s [datasets](https://scikit-learn.org/stable/api/sklearn.datasets.html) module. 
The dataset has $M=2048$ samples, and $N=2$ features. 

In [ ]:
from sklearn.datasets import make_circles
import numpy as np
import matplotlib.pyplot as plt
rng_seed = 3321

# features_raw, labels_raw = make_blobs(n_samples=2048, centers=np.array([[4, 4], [2, 1]]), cluster_std=1.0, random_state=3321)
features_raw, labels_raw = make_circles(n_samples=2048, shuffle=True, noise=0.1, random_state=rng_seed, factor=0.5)
# Visualize the raw data
plt.scatter(
    features_raw[:, 0], # feature 1 values (x coords)
    features_raw[:, 1], # feature 2 values (y coords)
    s=5*np.ones(labels_raw.size), # marker size all set to 1
    c=labels_raw, # colorized labels: 0:blue, 1:red
    cmap='coolwarm'  # color map
)


### <font color=#582C83>(5%) Exercise 1: Data Pre-Processing</font>
1. Implement a maximum scaling to the features so that the features are rescaled to the interval $[-1, 1]$.
2. To follow the convention in Linear Algebra, reshape labels array into a 2-dimension array as a column vector.

In [ ]:
### START CODING HERE ### (≈ 2 lines of code)
features_train = None  # max-scale features to interval: [-1, 1]
labels_train = None  # reshape labels to a column vector
### END CODING HERE ### 

# Sanity check
print(f"Samples of max-scaled features:\n {features_train[-4:]}")
print(f"Shape of max-scaled features:\n {features_train.shape}.")
print(f"Samples of reshaped labels:\n {labels_train[-4:]}")  # Print last 4 samples of features and labels
print(f"Shape of reshaped labels:\n {labels_train.shape}")  # Print shapes of features and labels   

# Visualize
plt.scatter(
    features_train[:, 0], 
    features_train[:, 1], 
    s=5*np.ones(labels_train.size), 
    c=labels_train, 
    cmap='coolwarm'  # color map
)

**Expected Outcomes**:
```console
Samples of max-scaled features:
 [[ 0.33894904 -0.08088946]
 [-0.67719531 -0.38727521]
 [-0.53396025  0.48407507]
 [-0.14622006 -0.35573736]]
Shape of max-scaled features:
 (2048, 2).
Samples of reshaped labels:
 [[1]
 [0]
 [0]
 [1]]
Shape of reshaped labels:
 (2048, 1)
``` 

## 2. Create a Non-linear Multi-Input Single-Output Model
Let's create a nonlinear model by applying a sigmoid function to the output of a linear model.

$$\mathbf{\hat{y}} = \sigma (\mathbf{X} \cdot \mathbf{w}^T + \mathbf{b}) = \sigma(\mathbf{Z})$$

The sigmoid function can be represented as,

$$\sigma(\mathbf{Z}) = \frac{1}{1 + e^{-\mathbf{Z}}}$$

The linear part of the model is governed by a parameter vector 
$$\mathbf{w} = [w_1, w_2, ..., w_N]_{(1, N)}$$

and a bias vector 
$$\mathbf{b} = \begin{bmatrix} b \\ b \\ \vdots \\ b \end{bmatrix}_{(M, 1)}$$

And, in this practice $M=2048$ and $N=2$

### <font color=#582C83>(10%) Exercise 2: Model N01 Construction</font>
1. Define a linear function
2. Define the model function using `sigmoid` and `linear` functions

In [ ]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def linear(in_features, weights, bias):
    ### START CODING HERE ### (≈ 1 lines of code)
    out_features = None
    ### END CODING HERE ###
    return out_features

def model_n01(in_features, weights, bias):
    """
    Compute the linear combination of inputs and weights plus bias.
    
    Args:
        in_features (np.ndarray): Input features of shape (M, N).
        weights (np.ndarray): Weights of shape (1, N).
        bias (float): Bias term.  
    Returns:
        predictions: Linear combination result of shape (M, 1).
    """
    ### START CODING HERE ### (≈ 1 lines of code)
    predictions = None
    ### END CODING HERE ###
    return predictions

# Sanity check
w_dummy = np.array([[1.2, -2.3]])
b_dummy = -1.2
print(f"Samples of dummy prediction:\n {model_n01(features_train, w_dummy, b_dummy)[-4:]}")  # Print last 4 samples of dummy prediction

# Visualize dummy model decision boundary
plt.scatter(features_train[:, 0], features_train[:, 1], s=5*np.ones(labels_train.size), c=labels_train, cmap='coolwarm')
# Create a meshgrid of points over the feature space
xx, yy = np.meshgrid(np.linspace(-1.1, 1.1, 300),
                     np.linspace(-1.1, 1.1, 300))
zz = sigmoid(w_dummy[0, 0] * xx + w_dummy[0, 1] * yy + b_dummy) - 0.5
plt.contourf(xx, yy, zz, levels=[-np.inf, 0, np.inf], colors=['blue', 'red'], alpha=0.25)


**Expected Outcomes**:
>
```console
Samples of dummy prediction:
 [[0.35269466]
 [0.24565877]
 [0.04954192]
 [0.36417979]]
```

## 3. Evaluate Model
As same as the linear regression, we need to evaluate model performance. 
It is OK to use a Mean Squared Error (MSE) function, but a Binary Cross Entropy (BCE) function (below) is more suitable for such a problem. 

$$\mathcal{L}(\mathbf{\hat{y}}, \mathbf{y}) = \frac{1}{M} \Sigma [-\mathbf{y} \log \hat{\mathbf{y}} - (1 - \mathbf{y}) \log(1 - \hat{\mathbf{y}})]$$

Another metric for classification problems in general is the accuracy.
Let $TP$ be number of true positive predictions, $TN$ be number of true negative predictions, $FP$ be number of false positive predictions, $FN$ be number of false negative predictions.
The accuracy is defined as:
$$Accuracy = \frac{TP + TN}{TP+FP+TN+FN}$$

### <font color=#582C83>(10%) Exercise 3: Model Assessments</font>
1. Evaluate model loss with BCE function.
2. Assess model predictions accuracy.

In [ ]:
def bce_loss(predictions, labels):
    """
    Compute the Binary Cross Entropy (BCE) loss.
    
    Args:
        predictions (np.ndarray): Predicted probabilities of shape (M, 1).
        labels (np.ndarray): True binary labels of shape (M, 1).
    Returns:
        loss: BCE loss value (float).
    """
    ### START CODING HERE ### (≈ 1 line)
    loss = None
    return loss
    ### END CODING HERE ###

def accuracy(predictions, labels):
    """
    Compute the accuracy of predictions.
    
    Args:
        predictions (np.ndarray): Predicted probabilities of shape (M, 1).
        labels (np.ndarray): True binary labels of shape (M, 1).
    Returns:
        acc: Accuracy value (float).
    """
    ### START CODING HERE ### (≈ 2 lines)
    predicted_classes = None  # Convert probabilities to binary classes
    acc = None
    return acc
    ### END CODING HERE ###

# Sanity check
preds_dummy = model_n01(features_train, w_dummy, b_dummy)
print(f"Dummy model BCE loss: {bce_loss(preds_dummy, labels_train)}")
print(f"Dummy model accuracy: {accuracy(preds_dummy, labels_train) * 100}%")

**Expected Output**:
>
```console
Dummy model BCE loss: 0.9925228865047314
Dummy model accuracy: 36.328125%
```

## 4. Compute Gradient of Loss
Compute gradient of the BCE loss:

$$\frac{\partial \mathcal{L}}{\partial \mathbf{w}} = \begin{bmatrix} \frac{\partial \mathcal{L}}{\partial w_1} & \frac{\partial \mathcal{L}}{\partial w_2} & \dots & \frac{\partial \mathcal{L}}{\partial w_N} \end{bmatrix} = \frac{1}{M} (\hat{\mathbf{y}} - \mathbf{y})^T \cdot \mathbf{X}$$
$$\frac{\partial \mathcal{L}}{\partial b}  = \overline{\hat{\mathbf{y}} - \mathbf{y}} $$

### <font color=#582C83>(5%) Exercise 4: Gradient of BCE Loss</font>

In [ ]:
### START CODING HERE ### (≈ 3 lines of code)

def gradient(predictions, labels, in_features):
    """
    Compute the gradient of the BCE loss with respect to weights and bias.
    
    Args:
        predictions (np.ndarray): Predicted probabilities of shape (M, 1).
        labels (np.ndarray): True binary labels of shape (M, 1).
        in_features (np.ndarray): Input features of shape (M, N).
    Returns:
        dw: Gradient with respect to weights of shape (1, N).
        db: Gradient with respect to bias (float).
    """
    M = None  # Number of samples
    dw = None  # Gradient w.r.t. weights
    db = None  # Gradient w.r.t. bias
    return dw, db

### END CODING HERE ###


# Sanity check
dw_dummy, db_dummy = gradient(preds_dummy, labels_train, features_train)
print(f"Dummy model gradient w.r.t. weights: {dw_dummy}, shape: {dw_dummy.shape}")
print(f"Dummy model gradient w.r.t. bias: {db_dummy}")

**Expected Output**:
>
```console
Dummy model gradient w.r.t. weights: [[ 0.04506402 -0.08373368]], shape: (1, 2)
Dummy model gradient w.r.t. bias: -0.21613454762096518
```

## 5. Update Model Parameters
By tweaking the model parameters along the gradient a small step (learning rate, $\alpha$) iteratively, we expect to bring the BCE loss down to a reasonable scale.

- $\text{Initialize } \mathbf{w} \text{ and } b$
- $\text{Repeat until converge}$
    - $\mathbf{w} = \mathbf{w} - \alpha \frac{\partial \mathcal{L}}{\partial \mathbf{w}}$
    - $b = b - \alpha \frac{\partial \mathcal{L}}{\partial b}$

    

### <font color=#582C83>(10%) Exercise 5: Model N01 Optimization</font>
1. Set learning rate and number of iterations
2. Initialize weights and bias
3. Repeat following steps:

    1. Make predictions
    2. Assess model
    3. Compute gradient of loss
    4. Update weights and bias

<font color=red>**Note: bring training accuracy over 50% within 500 iterations**</font>


In [ ]:
# START CODING HERE ### (≈ 10 lines of code)

# Set hyperparameters
learning_rate = None
num_iters = None

# Initialize model parameters
w = None  # randomly initialize weights
b = None  # randomly initialize bias

# Reserve loss and accuracy storage
losses_train = []
accuracies_train = []

# Training loop
for i in range(num_iters):
    preds_train = None  # Make predictions
    loss_train = None  # Assess model loss
    acc_train = None  # Assess model accuracy
    # Log training progress
    print(f"Iteration {i+1}/{num_iters}, Loss: {loss_train:.4f}, Accuracy: {acc_train*100:.2f}%")
    losses_train.append(loss_train)
    accuracies_train.append(acc_train)
    # Gradient descent
    dw, db = None  # Compute gradient of loss
    None  # Update weights
    None  # Update bias

### END CODING HERE ###


# Plot training loss and accuracy
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(losses_train, label='Training Loss')
plt.xlabel('Iteration')
plt.ylabel('BCE Loss')
plt.title('Training Loss over Iterations')
plt.legend()
plt.subplot(1, 2, 2)
plt.plot(np.array(accuracies_train) * 100, label='Training Accuracy', color='orange')
plt.xlabel('Iteration')
plt.ylabel('Accuracy (%)')
plt.title('Training Accuracy over Iterations')
plt.legend()   

### Visualize Decision Boundary for Model N01

In [ ]:
# Visualize decision boundary after training
plt.scatter(features_train[:, 0], features_train[:, 1], s=5*np.ones(labels_train.size), c=labels_train, cmap='coolwarm')
xx, yy = np.meshgrid(np.linspace(-1.1, 1.1, 300),
                     np.linspace(-1.1, 1.1, 300))
zz = sigmoid(w[0, 0] * xx + w[0, 1] * yy + b) - 0.5
plt.contourf(xx, yy, zz, levels=[-np.inf, 0, np.inf], colors=['blue', 'red'], alpha=0.25)
plt.title('Decision Boundary after Training')

## 6. Upgrade Model to Multi-Input, One-Hidden Layer, One-Output Format
By adding a hidden layer, the input features can be transformed to a higher (or lower) dimension space, which allowing the input features to be expressed in richer representations.

$$
\begin{align*} 
    \hat{\mathbf{y}} &= \sigma(\mathbf{X}^{[1]} \cdot \mathbf{w}^{[2]T} + \mathbf{b}^{[2]}) \\
    &= \sigma(\sigma(\mathbf{X}^{[0]} \cdot \mathbf{W}^{[1]T} + \mathbf{b}^{[1]}) \cdot \mathbf{w}^{[2]T} + \mathbf{b}^{[2]})
\end{align*}
$$

Where, $\mathbf{X}^{[1]}$ hosts the hidden features in a matrix with shape $(M, N_1)$ and the number of columns, $N_1$, is customizable. 
$\mathbf{X}^{[0]}$ contains the input features.

### <font color=#582C83>(10%) Exercise 6: Model N11 Construction</font>
Use the math above to define a `model_n11` function for the upgraded model: N11.
Please reuse the previous defined functions to implement a two-layer neural network with one hidden layer.


In [ ]:
### START CODING HERE ### (≈ 2 lines of code)

def model_n11(in_features, params):
    hidden_features = None
    predictions = None
    return predictions, hidden_features

### END CODING HERE ###


# Sanity check
np.random.seed(rng_seed)
params_dummy = {
    'W1': np.random.normal(size=(4, features_train.shape[1])),  # dimensions: 2 -> 4
    'b1': np.random.normal(size=(1, 4)),
    'W2': np.random.normal(size=(1, 4)),
    'b2': np.random.normal()
}

preds_dummy, hid_feats_dummy = model_n11(features_train, params_dummy)
print(f"Samples of hidden features: \n{hid_feats_dummy[-4:]}")
print(f"Shape of the hidden features: {hid_feats_dummy.shape}")
print(f"Samples of dummy predictions with N11: \n{preds_dummy[-4:]}")
print(f"Shape of the dummy predictions: {preds_dummy.shape}")
print(f"Samples of dummy prediction labels: \n{(preds_dummy[-4:] >= 0.5).astype(int)}")
print(f"Dummy model BCE loss: {bce_loss(preds_dummy, labels_train)}")
print(f"Dummy model accuracy: {accuracy(preds_dummy, labels_train) * 100}%")

# Visualize decision boundary of the dummy model
def plot_decision_boundary(features, labels, params, color_map='coolwarm'):
    # Set min and max values and give it some padding
    x_min, x_max = features[:, 0].min() - 0.1, features[:, 0].max() + 0.1
    y_min, y_max = features[:, 1].min() - 0.1, features[:, 1].max() + 0.1
    # Generate a grid of points with distance 0.01 between them
    xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.01), np.arange(y_min, y_max, 0.01))
    # Predict the function value for the whole grid
    zz = model_n11(np.c_[xx.ravel(), yy.ravel()], params)[0]
    zz = zz.reshape(xx.shape)
    # Plot the contour and training examples
    plt.contourf(xx, yy, zz, cmap=color_map, alpha=0.5)
    plt.scatter(
        features[:, 0], 
        features[:, 1], 
        c=labels, 
        s=5*np.ones(labels.size), 
        cmap=color_map, 
    )

plt.scatter(features_train[:, 0], features_train[:, 1], s=5*np.ones(labels_train.size), c=labels_train, cmap='coolwarm')
plot_decision_boundary(features_train, labels_train, params_dummy)



**Expected Output**:
>
```console
Samples of hidden features: 
[[0.70761183 0.24893012 0.78939894 0.3054041 ]
 [0.71801148 0.34263332 0.80236882 0.44488994]
 [0.44475449 0.51175795 0.84691656 0.43069558]
 [0.7477204  0.26766211 0.78745462 0.36836619]]
Shape of the hidden features: (2048, 4)
Samples of dummy predictions with N11: 
[[0.12523259]
 [0.12614445]
 [0.15162116]
 [0.12247771]]
Shape of the dummy predictions: (2048, 1)
Samples of dummy prediction labels: 
[[0]
 [0]
 [0]
 [0]]
Dummy model BCE loss: 1.0872126562184723
Dummy model accuracy: 50.0%
```

## 7. Back Propagate Gradient of Loss
Now, we have 2 sets of parameters: $\mathbf{W}^{[1]}$, $\mathbf{b}^{[1]}$ and $\mathbf{w}^{[2]}$, $b^{[2]}$.
The gradient of loss involves calculate partial derivatives of loss w.r.t. each model parameter. 
The Nobel Prize winning Back Propagation (BP) Algorithm will be applied to calculate gradient over $\mathbf{W}^{[1]}$, $\mathbf{b}^{[1]}$ first, then back propagate to the gradient over $\mathbf{w}^{[2]}$, $b^{[2]}$.

$$\frac{\partial \mathcal{L}}{\partial \mathbf{w}^{[2]}} = \frac{1}{M} (\mathbf{\hat{y}} - \mathbf{y})^T \cdot \mathbf{X}^{[1]}$$

$$\frac{\partial \mathcal{L}}{\partial b^{[2]}} = \overline{(\mathbf{\hat{y}} - \mathbf{y})}$$

$$\frac{\partial \mathcal{L}}{\partial \mathbf{X}^{[1]}} = (\mathbf{\hat{y}} - \mathbf{y})^T \cdot \mathbf{w}^{[2]}$$

$$\frac{\partial \mathcal{L}}{\partial \mathbf{W}^{[1]}} = \frac{1}{M} [(\mathbf{\hat{y}} - \mathbf{y}) \cdot \mathbf{w}^{[2]} * \mathbf{X}^{[1]} * (1 - \mathbf{X}^{[1]})]^T \cdot \mathbf{X}^{[0]}$$

$$
\frac{\partial \mathcal{L}}{\partial \mathbf{b}^{[1]}} = \overline{
    (\mathbf{\hat{y}} - \mathbf{y}) \cdot \mathbf{w}^{[2]} * \mathbf{X}^{[1]} * (1 - \mathbf{X}^{[1]})
} \text{, on 1st dimension}
$$

### <font color=#582C83>(20%) Exercise 7: Gradient of Loss Back Propagation</font>
Use the math above to define a `backward` function for calculating gradient of loss over the N11 model.


In [ ]:
### START CODING HERE ### (≈ 6 lines of code)

def backward(in_features, hidden_features, predictions, labels, params):
    M = None  # number of samples
    dL_dW2 = None
    dL_db2 = None
    dL_dX1 = None  # intermediate result for continue gradient computation
    dL_dW1 = None
    dL_db1 = None
    grads = {
        'dW2': dL_dW2,
        'db2': dL_db2,
        'dW1': dL_dW1,
        'db1': dL_db1
    }   

    return grads

### END CODING HERE ###


# Sanity check
grads_dummy = backward(features_train, hid_feats_dummy, preds_dummy, labels_train, params_dummy)
for k, v in grads_dummy.items():
    print(f"{k}: {v}") 
    print(f"Shape of {k}: {v.shape}")  

**Expected Output**:
>
```console
dW2: [[-0.24170054 -0.11492614 -0.29552924 -0.12902307]]
Shape of dW2: (1, 4)
db2: -0.3676813508333104
Shape of db2: ()
dW1: [[-0.00024291  0.00093081]
 [-0.00061666  0.00015607]
 [-0.00038169  0.0011648 ]
 [ 0.00027938  0.00065294]]
Shape of dW1: (4, 2)
db1: [[ 0.08931597  0.05322645 -0.04613791 -0.04386565]]
Shape of db1: (1, 4)
```

## 8. Update Model N11 using Gradient Descent Algorithm
The Gradient Descent Algorithm stays the same:
- $\text{Initialize } \mathbf{w} \text{ and } b$
- $\text{Repeat until converge}$
    - $\mathbf{w} = \mathbf{w} - \alpha \frac{\partial \mathcal{L}}{\partial \mathbf{w}}$
    - $b = b - \alpha \frac{\partial \mathcal{L}}{\partial b}$

    

### <font color=#582C83>(15%) Exercise 8: Model N11 Optimization</font>
1. Set hyper-parameters: number of iterations, learning rate, and hidden layer size/dimensions 
2. Initialize weights and bias using a [Python dictionary](https://docs.python.org/3/tutorial/datastructures.html#dictionaries)
3. Repeat:

    1. Make predictions
    2. Assess model
    3. Back propagate gradient of loss
    4. Update weights and bias

<font color=red>**Note: bring training accuracy over 99% within 1000 iterations**</font>


In [ ]:
### START CODING HERE ### (≈ 15 lines of code)

# Set hyperparameters
num_iters = 1000
learning_rate = 0.3
hidden_size = 64

# Initialize parameters
params = {
    'W1': None,  # (N_1, N_0)
    'b1': None,  # (1, N_1)
    'W2': None,  # (1, N_1)
    'b2': None,  # ()
}

# Reserve metrics storage
losses_train = []
accuracies_train = []

# Optimization iterations
for i in range(num_iters):
    # Forward pass
    preds_train, hid_feats_train = None
    # Compute loss and accuracy
    loss_train = None
    acc_train = None
    # Log progress (every 50 iterations)   
    losses_train.append(loss_train)
    accuracies_train.append(acc_train)
    if i % 50 == 0 or i == num_iters - 1:
        print(f"Iter {i}: Train Loss {loss_train}, Train Acc {acc_train}")
    # Back-propagation
    grads = None
    # Gradient descent parameter update
    params['W1'] = None
    params['b1'] = None
    params['W2'] = None
    params['b2'] = None

### END CODING HERE ###


# Plot training loss and accuracy
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(losses_train, label='Training Loss')
plt.xlabel('Iteration')
plt.ylabel('BCE Loss')
plt.title('Training Loss over Iterations')
plt.legend()
plt.subplot(1, 2, 2)
plt.plot(np.array(accuracies_train) * 100, label='Training Accuracy', color='orange')
plt.xlabel('Iteration')
plt.ylabel('Accuracy (%)')
plt.title('Training Accuracy over Iterations')
plt.legend()   

### Visualize N11 classifier on training dataset

In [ ]:
plt.scatter(features_train[:, 0], features_train[:, 1], s=5*np.ones(labels_train.size), c=labels_train, cmap='coolwarm')
plot_decision_boundary(features_train, labels_train, params)


## 9. Validate Model with a Different Dataset
Let's generate a validation dataset using [make_circles](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_circles.html#sklearn.datasets.make_circles) again.
It has similar data distribution but different samples from the training dataset. 
The validation dataset contains 1000 samples with 900 belong to class 0, and 100 belong to class 1.

Let's apply the trained N11 model to the validation dataset.
A [confusion matrix](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.ConfusionMatrixDisplay.html) summarizes the performance of the N11 model on the validation dataset.

In [ ]:
# Load and preprocess validation data
X_raw, y_raw = make_circles(n_samples=(900, 100), shuffle=True, noise=0.13, factor=0.5)
features_val = X_raw / X_raw.max(axis=0)  # Scale features to [-1, 1]
labels_val = y_raw.reshape(-1, 1)  # Reshape labels to be a column vector

# Visualize validation data
plt.scatter(
    features_val[:, 0], 
    features_val[:, 1], 
    s=5*np.ones(labels_val.size), 
    c=labels_val, 
    cmap='bwr'  # color map
)

# Visualize decision boundary on validation data
plot_decision_boundary(features_val, labels_val, params, color_map='bwr')
plt.title('Classification over Validation Data')

# Confusion Matrix for Test Data
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
preds_val = model_n11(features_val, params)[0]
cm_val = confusion_matrix(labels_val, (preds_val >= 0.5).astype(int))
disp_val = ConfusionMatrixDisplay(confusion_matrix=cm_val, display_labels=['Negative', 'Positive'])
disp_val.plot(cmap='PuRd')
plt.title('Confusion Matrix - Validation Data')

### <font color=#582C83>(5%) Exercise 9: Classification Metrics</font>
According to the validation result and the confusion matrix, please calculate the following metrics and write your answers below.

- `Accuracy`=?
- `Recall`=?
- `Precision`=?




### <font color=#582C83>(15%) Exercise 10: Validation Analyses</font>
Assume the model is used by a factory's quality control department to detect defective (**positive**) products over 1000 samples (validation data).
Please answer the following questions **according to last exercise's statistcs**.

#### 1. Is the model good at picking out the defective products? Why?
> Answer

#### 2. What is the major problem the model could cause to the factory?
> Answer

# Congratulations! You have finished this assignment!